name: Bench
on: [push]

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          profile: default
          default: true
      - run: cargo bench --features std-mutex
      - run: cargo bench --features parking-lot-mutex
